export interface IManuallyTransmittedDataForFieldsFormSignUpPage {
	login: IManuallyTransmittedDataForTextFields;
	userName: IManuallyTransmittedDataForTextFields;
	password: IManuallyTransmittedDataForTextFields;
	repeatPassword: IManuallyTransmittedDataForTextFields;
	secretPhrase: IManuallyTransmittedDataForTextFields;
	acceptanceOfTermsPoliciesAndRules: IManuallyTransmittedDataForCheckboxFields;
	button: IManuallyTransmittedDataForButton;
};
