import type {
	ISchemeForForm,
	IInstanceRules
} from './schemes';

import {
	schemeFormSignInPage,
	schemeFormSignUpPage,
	schemeFormRecoveryAccountPage
} from './schemes';

import {
	IS_REQUIRED,
	MIN,
	MAX,
	NUMBER_REQUIRED,
	SYMBOL_REQUIRED,
	UPPER_CASE_ELEMENT_REQUIRED,
	IS_IDENTICAL
} from './names-rules';

import {
	APP_EVENT_CLICK,
	BUTTON_LOCK_EVENT_CLICK,
	BUTTON_DOTS_EVENT_CLICK,
	MODAL_EMPTY_SPACE_EVENT_CLICK,
	BUTTON_CLOSE_EVENT_CLICK,
	BUTTON_RED_EVENT_CLICK,
	BUTTON_WITH_DYNAMIC_BACKGROUND,
	BUTTON_ARROWS_EVENT_CLICK,
	COLUMN_MODULE_EVENT_METHOD,
	SLOT_MODULE_EVENT_METHOD
} from './event-emitter-events';

import {
	COLUMN_EVENT_SEGMENT,
	SLOT_EVENT_SEGMENT,
	MODAL_EVENT_SEGMENT,
	ADD_SLOT_EVENT_SEGMENT,
	DELETE_COLUMN_EVENT_SEGMENT,
	UPDATE_COLUMN_EVENT_SEGMENT,
	DELETE_SLOT_EVENT_SEGMENT,
	CLEAR_SLOT_EVENT_SEGMENT,
	ADD_COLUMN_EVENT_SEGMENT,
	MOVING_DOWN_SLOT_EVENT_SEGMENT,
	SHOW_SOCIAL_NETWORK_EVENT_SEGMENT,
	LOG_OUT_AUTHORIZATION_EVENT_SEGMENT,
	MOVING_LEFT_COLUMN_EVENT_SEGMENT,
	MOVING_RIGHT_COLUMN_EVENT_SEGMENT,
	MOVING_BEGINNING_COLUMN_EVENT_SEGMENT,
	MOVING_ENDING_COLUMN_EVENT_SEGMENT,
	MOVING_UP_SLOT_EVENT_SEGMENT,
	MOVING_BEGINNING_SLOT_EVENT_SEGMENT,
	MOVING_ENDING_SLOT_EVENT_SEGMENT,
	SHOW_WHATS_NEW_EVENT_SEGMENT
} from './event-emitter-segments-events';

import {
	HOME,
	AUTH,
	ALL,
	SPACE
} from './router-paths';

import {
	RECOVERY_ACCOUNT_SEGMENT,
	SIGN_IN_SEGMENT,
	SIGN_UP_SEGMENT
} from './router-paths-segments';

export {
	IS_REQUIRED,
	MIN,
	MAX,
	NUMBER_REQUIRED,
	SYMBOL_REQUIRED,
	UPPER_CASE_ELEMENT_REQUIRED,
	IS_IDENTICAL,
	schemeFormSignInPage,
	schemeFormSignUpPage,
	schemeFormRecoveryAccountPage,
	HOME,
	AUTH,
	ALL,
	SPACE,
	RECOVERY_ACCOUNT_SEGMENT,
	SIGN_IN_SEGMENT,
	SIGN_UP_SEGMENT,
	APP_EVENT_CLICK,
	BUTTON_LOCK_EVENT_CLICK,
	COLUMN_EVENT_SEGMENT,
	BUTTON_DOTS_EVENT_CLICK,
	SLOT_EVENT_SEGMENT,
	MODAL_EMPTY_SPACE_EVENT_CLICK,
	BUTTON_CLOSE_EVENT_CLICK,
	MODAL_EVENT_SEGMENT,
	BUTTON_RED_EVENT_CLICK,
	BUTTON_WITH_DYNAMIC_BACKGROUND,
	ADD_SLOT_EVENT_SEGMENT,
	DELETE_COLUMN_EVENT_SEGMENT,
	UPDATE_COLUMN_EVENT_SEGMENT,
	DELETE_SLOT_EVENT_SEGMENT,
	CLEAR_SLOT_EVENT_SEGMENT,
	BUTTON_ARROWS_EVENT_CLICK,
	ADD_COLUMN_EVENT_SEGMENT,
	COLUMN_MODULE_EVENT_METHOD,
	MOVING_DOWN_SLOT_EVENT_SEGMENT,
	SHOW_SOCIAL_NETWORK_EVENT_SEGMENT,
	SLOT_MODULE_EVENT_METHOD,
	LOG_OUT_AUTHORIZATION_EVENT_SEGMENT,
	MOVING_LEFT_COLUMN_EVENT_SEGMENT,
	MOVING_RIGHT_COLUMN_EVENT_SEGMENT,
	MOVING_BEGINNING_COLUMN_EVENT_SEGMENT,
	MOVING_ENDING_COLUMN_EVENT_SEGMENT,
	MOVING_UP_SLOT_EVENT_SEGMENT,
	MOVING_BEGINNING_SLOT_EVENT_SEGMENT,
	MOVING_ENDING_SLOT_EVENT_SEGMENT,
	SHOW_WHATS_NEW_EVENT_SEGMENT
};

export type {
	ISchemeForForm,
	IInstanceRules
};
